library: ~/.config/library.db
directory: ~/Music

import:
  write: yes
  copy: no
  move: yes

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins: fetchart lyrics fromfilename

fetchart:
  lastfm_key: c071b447b9ac5524d638e497fdf89035
  sources: lastfm coverart itunes amazon albumart filesystem
